DROP DATABASE IF EXISTS BLOG_RECETAS;
CREATE DATABASE BLOG_RECETAS;
USE BLOG_RECETAS;

CREATE TABLE recetas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    ingredientes TEXT NOT NULL,
    instrucciones TEXT NOT NULL
);
select * from recetas;
